apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: springboot-gateway
spec:
  selector:
    istio: ingressgateway  # Use Istio's default ingress gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"  # Allow all hosts for local testing
